version: "3.9"

services:
#    client:
#        container_name: prakticum-client
#        image: prakticum-client
#        build:
#            context: .
#            dockerfile: Dockerfile.client
#            args:
#              CLIENT_PORT: ${CLIENT_PORT}
#        restart: always
#        ports:
#            - "${CLIENT_PORT}:80"
#        environment:
#          - CLIENT_PORT=${CLIENT_PORT}
#          - SERVER_PORT=${SERVER_PORT}
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PORT: ${POSTGRES_PORT}
          SERVER_PORT: ${SERVER_PORT}
        depends_on:
          - postgres

    postgres:
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      user: root
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ellevanova@gmail.com
        PGADMIN_DEFAULT_PASSWORD: secret
      user: root
      volumes:
        - ./tmp/pgadmindata:/var/lib/pgadmin
      ports:
        - "80:80"
